const CREATE_BRICK = 'CREATE_BRICK';
const CREATE_BRICK2 = 'CREATE_BRICK2';
const FETCH_USERNAME_SUCCESS = 'FETCH_USERNAME_SUCCESS';
const FETCH_USERNAME_FAILURE = 'FETCH_USERNAME_FAILURE';

export default {
  CREATE_BRICK,
  CREATE_BRICK2,
  FETCH_USERNAME_SUCCESS,
  FETCH_USERNAME_FAILURE
}