const CREATE_BRICK = 'CREATE_BRICK';
const FETCH_USERNAME_SUCCESS = 'FETCH_USERNAME_SUCCESS';
const FETCH_USERNAME_FAILURE = 'FETCH_USERNAME_FAILURE';
const FETCH_PRO_FORMA_SUCCESS = 'FETCH_PRO_FORMA_SUCCESS';
const FETCH_PRO_FORMA_FAILURE = 'FETCH_PRO_FORMA_FAILURE';
const FETCH_BRICKS_FAILURE = 'FETCH_BRICKS_FAILURE';
const FETCH_BRICKS_SUCCESS = 'FETCH_BRICKS_SUCCESS';
const FETCH_BRICK_FAILURE = 'FETCH_BRICK_FAILURE';
const FETCH_BRICK_SUCCESS = 'FETCH_BRICK_SUCCESS';
const SUBMIT_PRO_FORMA_SUCCESS = 'SUBMIT_PRO_FORMA_SUCCESS';
const SUBMIT_PRO_FORMA_FAILURE = 'SUBMIT_PRO_FORMA_FAILURE';


export default {
  FETCH_USERNAME_SUCCESS,
  FETCH_USERNAME_FAILURE,

  FETCH_BRICKS_FAILURE,
  FETCH_BRICKS_SUCCESS,

  FETCH_PRO_FORMA_SUCCESS,
  FETCH_PRO_FORMA_FAILURE,

  SUBMIT_PRO_FORMA_SUCCESS,
  SUBMIT_PRO_FORMA_FAILURE,

  FETCH_BRICK_FAILURE,
  FETCH_BRICK_SUCCESS,

  CREATE_BRICK,
}