const FETCH_USERNAME_SUCCESS = 'FETCH_USERNAME_SUCCESS';
const FETCH_USERNAME_FAILURE = 'FETCH_USERNAME_FAILURE';
const FETCH_PRO_FORMA_SUCCESS = 'FETCH_PRO_FORMA_SUCCESS';
const FETCH_PRO_FORMA_FAILURE = 'FETCH_PRO_FORMA_FAILURE';
const FETCH_BRICKS_FAILURE = 'FETCH_BRICKS_FAILURE';
const FETCH_BRICKS_SUCCESS = 'FETCH_BRICKS_SUCCESS';
const FETCH_BRICK_FAILURE = 'FETCH_BRICK_FAILURE';
const FETCH_BRICK_SUCCESS = 'FETCH_BRICK_SUCCESS';
const FETCH_SUBJECTS_FAILURE = 'FETCH_SUBJECTS_FAILURE';
const FETCH_SUBJECTS_SUCCESS = 'FETCH_SUBJECTS_SUCCESS';
const SAVE_BRICK_SUCCESS = 'SAVE_BRICK_SUCCESS';
const SAVE_BRICK_FAILURE = 'SAVE_BRICK_FAILURE';
const SAVE_QUESTION_SUCCESS = 'SAVE_QUESTION_SUCCESS';
const SAVE_QUESTION_FAILURE = 'SAVE_QUESTION_FAILURE';
const CREATE_BRICK_SUCCESS = 'CREATE_BRICK_SUCCESS';
const CREATE_BRICK_FAILURE = 'CREATE_BRICK_FAILURE';
const ASSIGN_EDITOR_SUCCESS = 'ASSIGN_EDITOR_SUCCESS';
const ASSIGN_EDITOR_FAILURE = 'ASSIGN_EDITOR_FAILURE';
const SEND_TO_PUBLISHER_SUCCESS = 'SEND_TO_PUBLISHER_SUCCESS';
const SEND_TO_PUBLISHER_CONFIRMED = 'SEND_TO_PUBLISHER_CONFIRMED';
const SEND_TO_PUBLISHER_FAILURE = 'SEND_TO_PUBLISHER_FAILURE';
const LOGIN_SUCCESS = 'LOGIN_SUCCESS';
const LOGIN_FAILURE = 'LOGIN_FAILURE';
const REGISTER_SUCCESS = 'REGISTER_SUCCESS';
const REGISTTER_FAILURE = 'REGISTTER_FAILURE';
const LOGOUT_SUCCESS = 'LOGOUT_SUCCESS';
const LOGOUT_FAILURE = 'LOGOUT_FAILURE';
const AUTHORIZED_SUCCESS = 'AUTHORIZED_SUCCESS';
const AUTHORIZED_FAILURE = 'AUTHORIZED_FAILURE';
const GET_USER_SUCCESS = 'GET_USER_SUCCESS';
const GET_USER_FAILURE = 'GET_USER_FAILURE';
const GET_NOTIFICATIONS_SUCCESS = 'GET_NOTIFICATIONS_SUCCESS';
const GET_NOTIFICATIONS_FAILURE = 'GET_NOTIFICATIONS_FAILURE';
const RECEIVED_NOTIFICATION = 'RECEIVED_NOTIFICATION';
const NOTIFICATION_CLEAR = 'NOTIFICATION_CLEAR';
const NOTIFICATION_CLEAR_ALL = 'NOTIFICATION_CLEAR_ALL';
const NOTIFICATION_RESET = 'NOTIFICATION_RESET';
const NOTIFICATION_CHANGED = 'NOTIFICATION_CHANGED';
const NOTIFICATION_LATEST_DISMISSED = 'NOTIFICATION_LATEST_DISMISSED';
const GET_COMMENTS_SUCCESS = 'GET_COMMENTS_SUCCESS';
const GET_COMMENTS_FAILURE = 'GET_COMMENTS_FAILURE';
const EDIT_COMMENT = 'EDIT_COMMENT';
const CREATE_COMMENT_SUCCESS = 'CREATE_COMMENT_SUCCESS';
const CREATE_COMMENT_FAILURE = 'CREATE_COMMENT_FAILURE';
const NEW_COMMENT = 'NEW_COMMENT';
const DELETE_COMMENT = 'DELETE_COMMENT';
const FORGET_BRICK = 'FORGET_BRICK';
const AUTH_PROFILE_REDIRECT = 'AUTH_PROFILE_REDIRECT';
const AUTH_DEFAULT_USER_PROPERTIES = 'AUTH_DEFAULT_USER_PROPERTIES';
const GET_CLASS_STATS_SUCCESS = 'GET_CLASS_STATS_SUCCESS';
const GET_CLASS_STATS_FAILURE = 'GET_CLASS_STATS_FAILURE';
const REQUEST_FAILED = 'REQUEST_FAILED';
const REQUEST_FAILTURE_FORGOTTEN = 'REQUEST_FAILTURE_FORGOTTEN';

export default {
  REQUEST_FAILED,
  REQUEST_FAILTURE_FORGOTTEN,

  FETCH_USERNAME_SUCCESS,
  FETCH_USERNAME_FAILURE,

  FETCH_BRICKS_FAILURE,
  FETCH_BRICKS_SUCCESS,

  FETCH_PRO_FORMA_SUCCESS,
  FETCH_PRO_FORMA_FAILURE,

  SAVE_BRICK_SUCCESS,
  SAVE_BRICK_FAILURE,

  SAVE_QUESTION_SUCCESS,
  SAVE_QUESTION_FAILURE,

  CREATE_BRICK_SUCCESS,
  CREATE_BRICK_FAILURE,

  ASSIGN_EDITOR_SUCCESS,
  ASSIGN_EDITOR_FAILURE,

  SEND_TO_PUBLISHER_SUCCESS,
  SEND_TO_PUBLISHER_CONFIRMED,
  SEND_TO_PUBLISHER_FAILURE,

  FETCH_BRICK_FAILURE,
  FETCH_BRICK_SUCCESS,

  FETCH_SUBJECTS_FAILURE,
  FETCH_SUBJECTS_SUCCESS,

  LOGIN_SUCCESS,
  LOGIN_FAILURE,

  AUTH_PROFILE_REDIRECT,
  AUTH_DEFAULT_USER_PROPERTIES,

  REGISTER_SUCCESS,
  REGISTTER_FAILURE,

  LOGOUT_SUCCESS,
  LOGOUT_FAILURE,

  AUTHORIZED_SUCCESS,
  AUTHORIZED_FAILURE,

  GET_USER_SUCCESS,
  GET_USER_FAILURE,

  GET_NOTIFICATIONS_SUCCESS,
  GET_NOTIFICATIONS_FAILURE,

  RECEIVED_NOTIFICATION,
  NOTIFICATION_CLEAR,
  NOTIFICATION_CLEAR_ALL,
  NOTIFICATION_RESET,
  NOTIFICATION_CHANGED,
  NOTIFICATION_LATEST_DISMISSED,

  GET_COMMENTS_SUCCESS,
  GET_COMMENTS_FAILURE,

  EDIT_COMMENT,

  CREATE_COMMENT_SUCCESS,
  CREATE_COMMENT_FAILURE,

  NEW_COMMENT,
  DELETE_COMMENT,

  FORGET_BRICK,

  GET_CLASS_STATS_SUCCESS,
  GET_CLASS_STATS_FAILURE
}